[package]
name = "ao"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.2", features = ["derive"] }
anyhow = "1.0"
toml = "0.8" # Added for TOML parsing
serde = { version = "1.0", features = ["derive"] } # Added for deserialization

[dev-dependencies]
tempfile = "3.10"