[project]
name = "anops-dev"

[check]
linters = []
testers = [
    "pytest --cov=server.py --cov-report=term --maxfail=1 --disable-warnings -C model-service/tests",
    "pytest --cov=main.py --cov-report=term --maxfail=1 --disable-warnings -C api-service/tests",
    "pytest --maxfail=1 --disable-warnings -C tests"
]

# [tasks]
# my-task = ["echo hello"]