# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: anops.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'anops.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61nops.proto\x12\x05\x61nops\"$\n\x0ePredictRequest\x12\x12\n\ninput_data\x18\x01 \x01(\t\"&\n\x0fPredictResponse\x12\x13\n\x0boutput_data\x18\x01 \x01(\t2C\n\x05\x41nOps\x12:\n\x07Predict\x12\x15.anops.PredictRequest\x1a\x16.anops.PredictResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'anops_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREDICTREQUEST']._serialized_start=22
  _globals['_PREDICTREQUEST']._serialized_end=58
  _globals['_PREDICTRESPONSE']._serialized_start=60
  _globals['_PREDICTRESPONSE']._serialized_end=98
  _globals['_ANOPS']._serialized_start=100
  _globals['_ANOPS']._serialized_end=167
# @@protoc_insertion_point(module_scope)
